language: node_js

node_js:
  - "12.18.0"

script:
  - npm run build

deploy:
  provider: pages
  skip-cleanup: true
  local_dir: build
  github-token: $GITHUB_TOKEN
  keep-history: true
  target_branch: gh-pages
  on:
    branch: master
